---
title: "Final Project Rough Draft"
author: "Mark Hammond"
date: "2/27/2019"
output: html_document
---

```{r setup, include = FALSE, message = FALSE, warning = FALSE}
require(tidyverse)
library(data.table)
library(colorblindr)
library(gghighlight)
library(lubridate)
library(forcats)

knitr::opts_chunk$set(message = FALSE, error = FALSE, warning = FALSE)
#AAC: I might consider putting the chunk set option that eliminates the error and warning messages for the rmd and/or this chunk and/or sets figure width and height
```


```{r data import, include = F}
yrbs1 <-fread("SADCQ_a-m.csv") #AAC: I was unable to get this to load, and I don't think this data is included in the github repo. However, I was able to open the html doc in the repo, so I will leave comments in the rmd based on the plots denoted in the html. Let me know if I'm totally missing something. You might consider using the here package to load the data. 
yrbs2 <-fread("SADCQ_n-z.csv")

yrbs <- bind_rows(yrbs1, yrbs2)
laws <- rio::import("marijuana policy dates.xlsx") #AAC: Cool dataset and interesting variables examined!
```

```{r data prep, include = F}
yrbs <- yrbs %>%
  unite(key, year, sitecode, remove = F) #AAC: this is a new command for me and learned about this command from your code. I will definitely use it in the future
head(yrbs)

# Marijuana
l1 <- yrbs %>% 
  group_by(key, year, sitecode) %>% 
  mutate(evermar = ifelse(q46 > 1, "mar_y", "mar_n")) %>% #AAC: I always forget about using the ifelse command when wrangling and prepping my data. Great use of it here, and a great reminder to me :D 
  count(evermar) %>%
  spread(evermar, n) %>%
  summarise(evermar_perc = 100*(sum(mar_y)/nrow(yrbs))) %>%
  ungroup()
# Alcohol
l2 <- yrbs %>% 
  group_by(key) %>% 
  mutate(everalc = ifelse(q40 > 1, "alc_y", "alc_n")) %>%
  count(everalc) %>%
  spread(everalc, n) %>%
  summarise(everalc_perc = 100*(sum(alc_y)/nrow(yrbs))) %>%
  ungroup()
# Cigarettes
l3 <- yrbs %>% 
  group_by(key) %>% 
  mutate(evercig = ifelse(q32 > 1, "cig_y", "cig_n")) %>%
  count(evercig) %>%
  spread(evercig, n) %>%
  summarise(evercig_perc = 100*(sum(cig_y)/nrow(yrbs))) %>%
  ungroup()
l1
# Pulling it all together
law_full <- left_join(l1, l2, by = "key") %>%
                left_join(., l3, by = "key") %>%
                left_join(., laws, by = "sitecode") %>% 
  group_by(Law, year) %>% 
  summarise(alc_prop = mean(everalc_perc),
            cig_prop = mean(evercig_perc),
            mar_prop = mean(evermar_perc),
                alc_sd = sd(everalc_perc),
                cig_sd = sd(evercig_perc),
                mar_sd = sd(evermar_perc)) %>%
  ungroup() %>% 
      rename(Alcohol = alc_prop) %>%
      rename(Cigarettes = cig_prop) %>%
      rename(Marijuana = mar_prop) %>% 
  gather(drug, drug_prop, Alcohol:Marijuana) %>% 
  gather(drug_, drug_sd, alc_sd:mar_sd) %>% 
  select(Law, year, drug, drug_prop, drug_sd)
law_full

#AAC: It looks like you did a lot of great tidying and wrangling here to get your data ready for plotting! Great job.
```

# Plot 1.
```{r viz 1}
ggplot(law_full, aes(year, drug_prop, color = drug)) +
  geom_smooth(aes(fill = drug), alpha = 0.3) + 
    scale_fill_OkabeIto(name = "Substance", #AAC: I think there is a bit of confusion between the fill and color items here. I think the color is the one that denotes the color of the lines and fill denotes the color of the se ribbon? (not totally sure about this and can't run the code with the data). However, I think it would look the best that the line color and the ribbon color match, and that there is only one legend on the right, instead of two legends. The two legends are also not in the same order. 
                       labels = c("Alcohol", "Marijuana", "Cigarettes")) +
  scale_y_continuous("Percentage", labels = scales::percent) + #AAC: I actually didn't know you could use this function to name the x and y axes (I always use labsto name them), so this was good to learn from you -thanks!
  scale_x_continuous("Year", limits = c(1995, 2015)) +
  labs(title = "Prevalence of Underage Substance Use Over 20 Years",
       caption = "Data from the CDC's Youth Risk Behavior Survey") +
  theme_minimal()

#AAC: Great use of the scales function for your y axis, and I loved how you used the caption to denote the source of the data. Great use of line plot to represent data change over time
```


```{r data prep 2, include = F}
# Pulling it all together
law_full2 <- left_join(l1, l2, by='key') %>%
                left_join(., l3, by='key') %>%
                left_join(., laws, by = "sitecode") %>% 
  group_by(Law, year, sitecode) %>% 
  summarise(alc_prop = mean(everalc_perc),
            cig_prop = mean(evercig_perc),
            mar_prop = mean(evermar_perc),
                alc_sd = sd(everalc_perc),
                cig_sd = sd(evercig_perc),
                mar_sd = sd(evermar_perc)) %>%
  ungroup() %>% 
      rename(Alcohol = alc_prop) %>%
      rename(Cigarettes = cig_prop) %>%
      rename(Marijuana = mar_prop) %>% 
  gather(drug, drug_prop, Alcohol:Marijuana) %>% 
  gather(drug_, drug_sd, alc_sd:mar_sd) %>% 
  select(Law, year, sitecode, drug, drug_prop, drug_sd)
law_full2

#AAC: Again, great tidying!
```

# Plot 2.
```{r viz 2}

ggplot(law_full2, aes(year, drug_prop, col = drug)) +
    geom_smooth(aes(fill = drug), alpha = 0.3) + 
    scale_fill_OkabeIto(name = "Substance", #AAC: Same comment above regarding the fill/color discrepancy, but great palette choice - i love the okabeito colors
                       labels = c("Alcohol", "Marijuana", "Cigarettes")) +
  scale_y_continuous("Percentage", labels = scales::percent) +
  scale_x_continuous("Year") +
  facet_grid(.~Law) +
  labs(title = "Underage Substance Use By State Marijuana Policy",
       caption = "Data from the CDC's Youth Risk Behavior Survey") +
  theme(panel.spacing = unit(10, "lines")) + #I didn't know you could select the panel spacing for faceted plots within theme, this is cool! Thanks for the tip (: 
  theme_minimal(12) #oooooh, I didn't know there were multiple theme minimals that you could choose from!

#Again, approprite use of line plot to show change over time, and great use of faceting to show differences in the change over time between groups. Also, the plot looks really cool too! I would like to see the size of the plot stretched out a bit horizontally to get a better sense of the change over time in each group, which you can do using fig.width = . I'd also like to know how many states are in each group and who these NA states are. 

```

```{r data prep 3, include = F}
mar_pol <- yrbs %>% 
  group_by(key, year, sitecode) %>% 
  mutate(evermar = ifelse(q46 > 1, "mar_y", "mar_n")) %>%
  count(evermar) %>%
  spread(evermar, n) %>%
  summarise(evermar_perc = 100*(sum(mar_y)/nrow(yrbs))) %>%
  ungroup() %>% 
      left_join(., laws, by = "sitecode") %>% 
  group_by(Law, year, sitecode) %>% 
  summarise(mar_prop = mean(evermar_perc)) %>%
  ungroup() %>% 
      rename(Marijuana = mar_prop)
mar_pol

#Great tidying!
```

# Plot 3.
```{r viz 3}
mar_pol %>% 
  filter(Law == "recreational" | Law == "medical") %>% #You could use the janitor library to make all variable names lowercase (I think this is considered better coding practice, but I'm not sure why?)
  ggplot(year, Marijuana) +
    geom_line(aes(col = Law)) + #AAC: I think it might be better to denote at least the x and y variables in the main call to ggplot. 
  facet_wrap(~sitecode) +
  scale_y_continuous("Percentage", labels = scales::percent) +
  scale_x_continuous("Year") +
  labs(title = "Adolescent Marijuana Use Where Marijuana Use is Legal",
       caption = "Data from the CDC's Youth Risk Behavior Survey") +
  theme(panel.spacing = unit(10, "lines")) +
  theme_minimal(12)

#Again, great use of line plot to show change over time and use of faceting! I think the relationship that you highlighted with the group factor (type of legalization) is a really interesting one to examine. My only question is where is Oregon? :D I might consider changing the colors to be more color blind friendly (maybe keeping the use of okabe ito consistent).

#Overall, good job, I really enjoyed looking at your code and your plots. You really are a line graph and faceting expert. Also your coding style was really great and easily understandable. That being said, I would like to learn more about the intended audience of each of your plots and might explore different types of displaying data over time (maybe a heat map or an animated map of the country/states - just some ideas). 
```



